blank_issues_enabled: false
contact_links:
  - name: Other questions/Issues
    url: https://github.com/finos/common-domain-model/discussions/categories/q-a
    about: Please raise other questions/issues within discussions if your issue does not fall within any of the given templates.
